services:
    artis.shop_api_plugin.factory.shop.shop_info_view_factory:
        class: DH\ArtisShopApiPlugin\Factory\Shop\ShopInfoViewFactory
        public: true
        arguments:
            - "@sylius.repository.country"
