imports:
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopApiPlugin/Resources/config/app/sylius_mailer.yml" }
    - { resource: "@DHArtisShopApiPlugin/Resources/config/services.yml" }
